name: fatigueset_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - statsmodels=0.14.2
  - openpyxl
  - numpy
  - mne
  - scipy
  - ipympl